In [1]:
import pandas as pd

In [2]:
import pandas as pd
from scipy.sparse import csr_matrix

df = pd.read_csv('wikipedia-vectors.csv', index_col=0)

In [3]:
df

HTTP 404  Alexa Internet  Internet Explorer  HTTP cookie  \
0           0.0        0.000000           0.000000          0.0   
1           0.0        0.000000           0.000000          0.0   
2           0.0        0.029607           0.000000          0.0   
3           0.0        0.000000           0.000000          0.0   
4           0.0        0.000000           0.000000          0.0   
...         ...             ...                ...          ...   
13120       0.0        0.000000           0.000000          0.0   
13121       0.0        0.000000           0.000000          0.0   
13122       0.0        0.000000           0.011594          0.0   
13123       0.0        0.000000           0.000000          0.0   
13124       0.0        0.000000           0.000000          0.0   

       Google Search  Tumblr  Hypertext Transfer Protocol  Social search  \
0           0.000000     0.0                          0.0            0.0   
1           0.000000     0.0                          0.0            0.0   
2           0.000000     0.0                          0.0            0.0   
3           0.000000     0.0                          0.0            0.0   
4           0.000000     0.0                          0.0            0.0   
...              ...     ...                          ...            ...   
13120       0.000000     0.0                          0.0            0.0   
13121       0.000000     0.0                          0.0            0.0   
13122       0.000000     0.0                          0.0            0.0   
13123       0.006649     0.0                          0.0            0.0   
13124       0.000000     0.0                          0.0            0.0   

       Firefox  LinkedIn  ...  Chad Kroeger  Nate Ruess  The Wanted  \
0          0.0       0.0  ...           0.0         0.0         0.0   
1          0.0       0.0  ...           0.0         0.0         0.0   
2          0.0       0.0  ...           0.0         0.0         0.0   
3          0.0       0.0  ...           0.0         0.0         0.0   
4          0.0       0.0  ...           0.0         0.0         0.0   
...        ...       ...  ...           ...         ...         ...   
13120      0.0       0.0  ...           0.0         0.0         0.0   
13121      0.0       0.0  ...           0.0         0.0         0.0   
13122      0.0       0.0  ...           0.0         0.0         0.0   
13123      0.0       0.0  ...           0.0         0.0         0.0   
13124      0.0       0.0  ...           0.0         0.0         0.0   

       Stevie Nicks  Arctic Monkeys  Black Sabbath  Skrillex  \
0          0.008878             0.0            0.0  0.049502   
1          0.000000             0.0            0.0  0.000000   
2          0.000000             0.0            0.0  0.000000   
3          0.000000             0.0            0.0  0.000000   
4          0.000000             0.0            0.0  0.000000   
...             ...             ...            ...       ...   
13120      0.000000             0.0            0.0  0.000000   
13121      0.000000             0.0            0.0  0.000000   
13122      0.000000             0.0            0.0  0.000000   
13123      0.000000             0.0            0.0  0.000000   
13124      0.000000             0.0            0.0  0.000000   

       Red Hot Chili Peppers    Sepsis  Adam Levine  
0                   0.000000  0.000000          0.0  
1                   0.000000  0.006110          0.0  
2                   0.000000  0.000000          0.0  
3                   0.005646  0.000000          0.0  
4                   0.000000  0.000000          0.0  
...                      ...       ...          ...  
13120               0.000000  0.000000          0.0  
13121               0.000000  0.000000          0.0  
13122               0.000000  0.000000          0.0  
13123               0.000000  0.005476          0.0  
13124               0.000000  0.000000          0.0  

[13125 rows x 60 c

In [4]:
articles = csr_matrix(df.transpose())
titles = list(df.columns)

In [17]:
vocabulary=open('wikipedia-vocabulary-utf8.txt','r').read()
vocabulary=vocabulary.split('\n')

In [20]:
data=pd.DataFrame(articles.toarray(),columns=vocabulary,index=titles)
data

aaron  abandon  abandoned  \
HTTP 404                                       0.000000  0.00000   0.000000   
Alexa Internet                                 0.000000  0.00000   0.029607   
Internet Explorer                              0.000000  0.00000   0.000000   
HTTP cookie                                    0.000000  0.00000   0.000000   
Google Search                                  0.000000  0.00000   0.000000   
Tumblr                                         0.000000  0.00000   0.000000   
Hypertext Transfer Protocol                    0.000000  0.00000   0.000000   
Social search                                  0.000000  0.00000   0.000000   
Firefox                                        0.000000  0.00000   0.000000   
LinkedIn                                       0.000000  0.00000   0.000000   
Global warming                                 0.000000  0.00000   0.000000   
Nationally Appropriate Mitigation Action       0.000000  0.00000   0.000000   
Nigel Lawson                                   0.000000  0.00000   0.000000   
Connie Hedegaard                               0.000000  0.00000   0.000000   
Climate change                                 0.000000  0.00000   0.000000   
Kyoto Protocol                                 0.000000  0.00000   0.000000   
350.org                                        0.000000  0.00000   0.000000   
Greenhouse gas emissions by the United States  0.000000  0.00000   0.000000   
2010 United Nations Climate Change Conference  0.000000  0.00000   0.000000   
2007 United Nations Climate Change Conference  0.000000  0.00000   0.000000   
Angelina Jolie                                 0.000000  0.00000   0.017294   
Michael Fassbender                             0.000000  0.00000   0.000000   
Denzel Washington                              0.000000  0.00000   0.000000   
Catherine Zeta-Jones                           0.020076  0.00000   0.000000   
Jessica Biel                                   0.000000  0.00000   0.000000   
Russell Crowe                                  0.000000  0.00000   0.000000   
Mila Kunis                                     0.000000  0.00000   0.000000   
Dakota Fanning                                 0.000000  0.00000   0.000000   
Anne Hathaway                                  0.000000  0.00000   0.000000   
Jennifer Aniston                               0.000000  0.00000   0.000000   
France national football team                  0.000000  0.00000   0.000000   
Cristiano Ronaldo                              0.000000  0.00000   0.000000   
Arsenal F.C.                                   0.000000  0.00000   0.000000   
Radamel Falcao                                 0.000000  0.00000   0.007054   
Zlatan Ibrahimović                             0.000000  0.00000   0.006915   
Colombia national football team                0.000000  0.00000   0.000000   
2014 FIFA World Cup qualification              0.000000  0.00000   0.014745   
Football                                       0.000000  0.00000   0.000000   
Neymar                                         0.000000  0.00000   0.000000   
Franck Ribéry                                  0.000000  0.00000   0.000000   
Tonsillitis                                    0.000000  0.00000   0.000000   
Hepatitis B                                    0.000000  0.00000   0.000000   
Doxycycline                                    0.000000  0.00000   0.000000   
Leukemia                                       0.000000  0.00000   0.000000   
Gout                                           0.000000  0.00000   0.000000   
Hepatitis C                                    0.000000  0.00000   0.000000   
Prednisone                                     0.000000  0.00000   0.000000   
Fever                                          0.000000  0.00000   0.000000   
Gabapentin                                     0.000000  0.00000   0.000000   
Lymphoma                                       0.000000  0.00000   0.020774   
Chad Kroeger         

In [22]:
# Import NMF
from sklearn.decomposition import NMF

# Create an NMF instance: model
model = NMF(n_components=6)

# Fit the model to articles
model.fit(data)

# Transform the articles: nmf_features
nmf_features = model.transform(data)

# Print the NMF features
print(nmf_features.round(2))

[[0.   0.   0.   0.   0.   0.44]
 [0.   0.   0.   0.   0.   0.57]
 [0.   0.   0.   0.   0.   0.4 ]
 [0.   0.   0.   0.   0.   0.38]
 [0.   0.   0.   0.   0.   0.49]
 [0.01 0.01 0.01 0.03 0.   0.33]
 [0.   0.   0.02 0.   0.01 0.36]
 [0.   0.   0.   0.   0.   0.49]
 [0.02 0.01 0.   0.02 0.03 0.48]
 [0.01 0.03 0.03 0.07 0.02 0.34]
 [0.   0.   0.53 0.   0.03 0.  ]
 [0.   0.   0.36 0.   0.   0.  ]
 [0.01 0.01 0.31 0.06 0.01 0.02]
 [0.   0.01 0.34 0.01 0.   0.  ]
 [0.   0.   0.43 0.   0.04 0.  ]
 [0.   0.   0.48 0.   0.   0.  ]
 [0.01 0.02 0.38 0.03 0.   0.01]
 [0.   0.   0.48 0.   0.   0.  ]
 [0.   0.01 0.55 0.   0.   0.  ]
 [0.   0.   0.47 0.   0.   0.  ]
 [0.   0.01 0.02 0.52 0.06 0.01]
 [0.   0.   0.   0.51 0.   0.  ]
 [0.   0.01 0.   0.42 0.   0.  ]
 [0.   0.   0.   0.44 0.   0.  ]
 [0.   0.   0.   0.5  0.   0.  ]
 [0.1  0.09 0.   0.38 0.   0.01]
 [0.   0.   0.   0.57 0.   0.01]
 [0.01 0.01 0.   0.47 0.   0.01]
 [0.   0.   0.   0.58 0.   0.  ]
 [0.   0.   0.   0.53 0.01 0.01]
 [0.   0.4

In [23]:
# Import pandas
import pandas as pd

# Create a pandas DataFrame: df
df = pd.DataFrame(nmf_features,index=titles)

# Print the row for 'Anne Hathaway'
print(df.loc['Anne Hathaway'])

# Print the row for 'Denzel Washington'
print(df.loc['Denzel Washington'])

0    0.003845
1    0.000000
2    0.000000
3    0.575697
4    0.000000
5    0.000000
Name: Anne Hathaway, dtype: float64
0    0.000000
1    0.005601
2    0.000000
3    0.422370
4    0.000000
5    0.000000
Name: Denzel Washington, dtype: float64


In [33]:
df

0         1         2  \
HTTP 404                                       0.000000  0.000000  0.000000   
Alexa Internet                                 0.000000  0.000000  0.000000   
Internet Explorer                              0.003821  0.000000  0.000000   
HTTP cookie                                    0.000000  0.000000  0.000000   
Google Search                                  0.000000  0.000000  0.000000   
Tumblr                                         0.012929  0.013789  0.007764   
Hypertext Transfer Protocol                    0.000000  0.000000  0.020676   
Social search                                  0.000000  0.000000  0.000000   
Firefox                                        0.015427  0.014282  0.003767   
LinkedIn                                       0.011174  0.031369  0.030951   
Global warming                                 0.000000  0.000000  0.530755   
Nationally Appropriate Mitigation Action       0.000000  0.000000  0.356533   
Nigel Lawson                                   0.012013  0.006501  0.312266   
Connie Hedegaard                               0.003935  0.006245  0.342396   
Climate change                                 0.004638  0.000000  0.434945   
Kyoto Protocol                                 0.000000  0.000000  0.483322   
350.org                                        0.005650  0.018354  0.376559   
Greenhouse gas emissions by the United States  0.000000  0.000000  0.480946   
2010 United Nations Climate Change Conference  0.000000  0.009019  0.551045   
2007 United Nations Climate Change Conference  0.000000  0.000000  0.466001   
Angelina Jolie                                 0.000000  0.011408  0.020867   
Michael Fassbender                             0.000000  0.000000  0.000000   
Denzel Washington                              0.000000  0.005601  0.000000   
Catherine Zeta-Jones                           0.000000  0.000000  0.000000   
Jessica Biel                                   0.000000  0.000000  0.000000   
Russell Crowe                                  0.098839  0.086006  0.003911   
Mila Kunis                                     0.000000  0.000000  0.000000   
Dakota Fanning                                 0.013147  0.010486  0.000000   
Anne Hathaway                                  0.003845  0.000000  0.000000   
Jennifer Aniston                               0.002252  0.001387  0.000000   
France national football team                  0.000000  0.407557  0.001857   
Cristiano Ronaldo                              0.001534  0.608187  0.000522   
Arsenal F.C.                                   0.005388  0.265023  0.000539   
Radamel Falcao                                 0.000000  0.644930  0.000000   
Zlatan Ibrahimović                             0.000000  0.608921  0.000000   
Colombia national football team                0.000000  0.343693  0.000000   
2014 FIFA World Cup qualification              0.006105  0.315320  0.015489   
Football                                       0.006474  0.213333  0.009496   
Neymar                                         0.007991  0.467606  0.000000   
Franck Ribéry                                  0.000000  0.642835  0.000000   
Tonsillitis                                    0.000000  0.000000  0.000000   
Hepatitis B                                    0.000000  0.000000  0.000000   
Doxycycline                                    0.000000  0.000299  0.002145   
Leukemia                                       0.000000  0.000000  0.000000   
Gout                                           0.001781  0.000784  0.014164   
Hepatitis C                                    0.000000  0.000000  0.000000   
Prednisone                                     0.000000  0.000000  0.003284   
Fever                                          0.000000  0.000262  0.036113   
Gabapentin                                     0.011252  0.002123  0.016098   
Lymphoma                                       0.000000  0.000000  0.000000   
Chad Kroeger             

In [36]:
import pandas as pd


components_df = pd.DataFrame(model.components_,columns=vocabulary)


print(components_df.shape)


component = components_df.iloc[0]

print(component.nlargest())

(6, 13125)
band        0.969125
album       0.922369
tour        0.353669
released    0.266510
song        0.262324
Name: 0, dtype: float64


In [32]:
components_df

aaron   abandon  abandoned  abandoning  abandonment  abbas  abbey  \
0  0.011376  0.001210   0.000000    0.001739     0.000136    0.0    0.0   
1  0.000000  0.000010   0.005663    0.000000     0.000002    0.0    0.0   
2  0.000000  0.000008   0.000000    0.000000     0.004691    0.0    0.0   
3  0.004148  0.000000   0.003056    0.000000     0.000614    0.0    0.0   
4  0.000000  0.000568   0.004917    0.000000     0.000000    0.0    0.0   
5  0.000139  0.000000   0.008749    0.000000     0.000185    0.0    0.0   

   abbreviated  abbreviation       abc  ...   zealand  zenith  zeppelin  \
0     0.002463  2.445951e-07  0.000834  ...  0.025781     0.0  0.008324   
1     0.000566  5.002420e-04  0.000000  ...  0.008106     0.0  0.000000   
2     0.000758  1.604148e-05  0.000000  ...  0.008730     0.0  0.000000   
3     0.002436  8.143454e-05  0.003985  ...  0.012594     0.0  0.000000   
4     0.000089  4.259174e-05  0.000000  ...  0.001809     0.0  0.000000   
5     0.008630  1.530473e-05  0.000000  ...  0.000000     0.0  0.000000   

       zero  zeus  zimbabwe  zinc      zone     zones  zoo  
0  0.000000   0.0       0.0   0.0  0.000000  0.000424  0.0  
1  0.001710   0.0       0.0   0.0  0.002813  0.000297  0.0  
2  0.001317   0.0       0.0   0.0  0.000000  0.000143  0.0  
3  0.000000   0.0       0.0   0.0  0.001742  0.006720  0.0  
4  0.000017   0.0       0.0   0.0  0.000192  0.001351  0.0  
5  0.000000   0.0       0.0   0.0  0.002401  0.001682  0.0  

[6 rows x 13125 columns]

# LCD_Digit

In [38]:
lcd=pd.read_csv('lcd-digits.csv')

In [39]:
lcd

0.0  0.0.1  0.0.2  0.0.3  0.0.4  0.0.5  0.0.6  0.0.7  0.0.8  0.0.9  ...  \
0   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4   0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
..  ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
94  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
95  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
96  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
97  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
98  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

    0.0.82  0.0.83  0.0.84  0.0.85  0.0.86  0.0.87  0.0.88  0.0.89  0.0.90  \
0      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
94     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
95     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
96     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
97     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
98     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

    0.0.91  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
..     ...  
94     0.0  
95     0.0  
96     0.0  
97     0.0  
98     0.0  

[99 rows x 104 columns]

In [40]:
# Import pyplot
from matplotlib import pyplot as plt

# Select the 0th row: digit
digit = lcd.iloc[0]

# Print digit
print(digit)

# Reshape digit to a 13x8 array: bitmap
bitmap = digit.reshape(13,8)

# Print bitmap
print(bitmap)

# Use plt.imshow to display bitmap
plt.imshow(bitmap, cmap='gray', interpolation='nearest')
plt.colorbar()
plt.show()


0.0       0.0
0.0.1     0.0
0.0.2     0.0
0.0.3     0.0
0.0.4     0.0
         ... 
0.0.87    0.0
0.0.88    0.0
0.0.89    0.0
0.0.90    0.0
0.0.91    0.0
Name: 0, Length: 104, dtype: float64


AttributeError: 'Series' object has no attribute 'reshape'

In [44]:
# Import pyplot
from matplotlib import pyplot as plt

# Select the 0th row: digit
digit = lcd.iloc[0]

# Print digit
print(digit)

# Reshape digit to a 13x8 array: bitmap
bitmap = digit.values.reshape((13,8))

0.0       0.0
0.0.1     0.0
0.0.2     0.0
0.0.3     0.0
0.0.4     0.0
         ... 
0.0.87    0.0
0.0.88    0.0
0.0.89    0.0
0.0.90    0.0
0.0.91    0.0
Name: 0, Length: 104, dtype: float64
